networks:
  lumora-web_default:
    name: lumora-web_default

services:
  traefik:
    image: traefik:2.11
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/acme.json:/acme.json
    networks:
      - lumora-web_default
    labels:
      - "traefik.enable=true"
      # Dashboard (optional, for debugging)
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.traefik.service=api@internal"

  # lumora-web:
  #   build: .
  #   container_name: lumora-web
  #   restart: unless-stopped
  #   networks:
  #     - lumora-web_default
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.lumora-web.rule=Host(`www.${DOMAIN}`) || Host(`${DOMAIN}`) && PathPrefix(`/`)"
  #     - "traefik.http.routers.lumora-web.entrypoints=websecure"
  #     - "traefik.http.routers.lumora-web.tls=true"
  #     - "traefik.http.routers.lumora-web.tls.certresolver=letsEncrypt"
  #     - "traefik.http.routers.lumora-web.priority=1"
  #     - "traefik.http.services.lumora-web.loadbalancer.server.port=80"

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_HOST=${DOMAIN}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://${DOMAIN}
      - GENERIC_TIMEZONE=${TZ:-Asia/Kolkata}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - lumora-web_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=letsEncrypt"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: --cleanup --include-restarting --include-stopped --schedule "0 0 3 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - lumora-web_default

volumes:
  n8n_data: