services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_PORT=${N8N_PORT}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_PAYLOAD_SIZE_MAX=${N8N_PAYLOAD_SIZE_MAX}
      - TZ=${TZ}
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=false
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./files:/files
    restart: unless-stopped

  # watchtower (optional auto‑updates at 03:00 daily). Leave commented for now.
  # watchtower:
  #   image: containrrr/watchtower
  #   command: --cleanup --include-restarting --include-stopped --schedule "0 0 3 * * *" n8n
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   restart: unless-stopped

volumes:
  n8n_data: {}